on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Saturn
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v30

    - name: Build
      run: nix build

    - name: Upload script
      uses: actions/upload-artifact@v4.4.3
      with:
        name: saturn
        path: ./result/bin/saturn
        
